import React, { useCallback } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  Platform,
} from "react-native";
import * as DocumentPicker from 'expo-document-picker';

const ACCEPTED_EXTENSIONS: string[] = [".csv", ".xlsx"];

// Artifact file prefixes generated by macOS ("._data.csv"), Windows Office ("~$teams.xlsx"), and hidden files
const ARTIFACT_PREFIXES = ["._", "~$", "."];

interface UploadedFile {
  name: string;
  size: number;
  type: string;
}
interface DropZoneProps {
  onFilesSelected: (files: UploadedFile[]) => void;
  isDragging: boolean;
  setIsDragging: (value: boolean) => void;
}

// Web-only drag-and-drop zone
export default function DropZone({
  onFilesSelected,
  isDragging,
  setIsDragging,
}: DropZoneProps): React.JSX.Element {
  const handleDragOver = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(true);
    },
    [setIsDragging]
  );

  const handleDragLeave = useCallback(() => {
    setIsDragging(false);
  }, [setIsDragging]);

  const handleDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(false);
      const droppedFiles = Array.from(e.dataTransfer.files).filter((f) => {
        const lower = f.name.toLowerCase();
        const hasValidExt = lower.endsWith('.csv') || lower.endsWith('.xlsx');
        const isArtifact = ARTIFACT_PREFIXES.some(p => f.name.startsWith(p));
        return hasValidExt && !isArtifact;
      }) as UploadedFile[];
      onFilesSelected(droppedFiles);
    },
    [onFilesSelected, setIsDragging]
  );

  const handleBrowse = useCallback(() => {
    const input = document.createElement("input");
    input.type = "file";
    input.multiple = true;
    input.accept = ACCEPTED_EXTENSIONS.join(",");
    input.onchange = (e: Event) => {
      const target = e.target as HTMLInputElement;
      if (target.files) {
        const selectedFiles = Array.from(target.files) as UploadedFile[];
        onFilesSelected(selectedFiles);
      }
    };
    input.click();
  }, [onFilesSelected]);

  return (
    <View
      style={Platform.OS === 'web'
        ? {
            borderRadius: 16,
            borderWidth: 2,
            borderStyle: 'dashed' as any,
            borderColor: isDragging ? '#facc15' : '#52525b',
            backgroundColor: isDragging ? 'rgba(250,204,21,0.05)' : 'rgba(39,39,42,0.3)',
            overflow: 'hidden',
          }
        : {
            borderRadius: 16,
            borderWidth: 1,
            borderColor: '#e5e7eb',
            backgroundColor: '#f9fafb',
            overflow: 'hidden',
          }
      }
    >
      {Platform.OS === "web" ? (
        <div
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          style={{ padding: 0 }}
        >
          <View className="items-center justify-center py-12 px-6 gap-4">
            {/* Upload icon */}
            <View
              className={`w-16 h-16 rounded-2xl items-center justify-center ${
                isDragging ? "bg-yellow-400/20" : "bg-zinc-700/50"
              }`}
            >
              <Text className="text-4xl">{isDragging ? "📂" : "☁️"}</Text>
            </View>

            {/* Heading */}
            <View className="items-center gap-1">
              <Text className="text-base text-lg font-semibold text-center">
                {isDragging ? "Release to upload" : "Drop files here"}
              </Text>
              <Text className="text-zinc-500 text-sm text-center">
                or{" "}
                <Text
                  className="text-yellow-400 font-semibold"
                  onPress={handleBrowse}
                  style={{ cursor: "pointer" }}
                >
                  browse your device
                </Text>
              </Text>
            </View>

            {/* Accepted types */}
            <View className="flex-row flex-wrap gap-1.5 justify-center mt-1">
                <Text className="text-zinc-500 text-xs w-full text-center mb-1">
                    Accepted file types:
                </Text>
              {ACCEPTED_EXTENSIONS.map((ext) => (
                <View key={ext} className="px-2 py-0.5 bg-zinc-700/60 rounded-md">
                  <Text className="text-zinc-400 text-xs font-mono">{ext}</Text>
                </View>
              ))}
            </View>

            <Text className="text-zinc-600 text-xs mt-1">Max file size: 50 MB</Text>
          </View>
        </div>
      ) : (
        // Native (iOS/Android) — document picker
        <TouchableOpacity
          onPress={async () => {
            const result = await DocumentPicker.getDocumentAsync({
              type: [
                'text/csv',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/comma-separated-values',
              ],
              multiple: true,
              copyToCacheDirectory: true,
            });
            if (result.canceled) return;
            const picked: UploadedFile[] = result.assets.map((a) => ({
              name: a.name,
              size: a.size ?? 0,
              type: a.mimeType ?? '',
            }));
            onFilesSelected(picked);
          }}
        >
          <View style={{ alignItems: 'center', justifyContent: 'center', paddingVertical: 48, paddingHorizontal: 24, gap: 12 }}>
            <View style={{ width: 64, height: 64, borderRadius: 16, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center' }}>
              <Text style={{ fontSize: 32 }}>📂</Text>
            </View>
            <View style={{ alignItems: 'center', gap: 4 }}>
              <Text style={{ fontSize: 16, fontWeight: '600', color: '#111827', textAlign: 'center' }}>
                Tap to browse files
              </Text>
              <Text style={{ fontSize: 13, color: '#6b7280', textAlign: 'center' }}>
                CSV and XLSX files accepted
              </Text>
            </View>
          </View>
        </TouchableOpacity>
      )}
    </View>
  );
}