import React, { useCallback } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  Platform,
} from "react-native";
import * as DocumentPicker from 'expo-document-picker';
import { useTheme } from '../contexts/ThemeContext';

const ACCEPTED_EXTENSIONS: string[] = [".csv", ".xlsx"];

// Artifact file prefixes generated by macOS ("._data.csv"), Windows Office ("~$teams.xlsx"), and hidden files
const ARTIFACT_PREFIXES = ["._", "~$", "."];

interface UploadedFile {
  name: string;
  size: number;
  type: string;
}
interface DropZoneProps {
  onFilesSelected: (files: UploadedFile[]) => void;
  isDragging: boolean;
  setIsDragging: (value: boolean) => void;
}

// Web-only drag-and-drop zone
export default function DropZone({
  onFilesSelected,
  isDragging,
  setIsDragging,
}: DropZoneProps): React.JSX.Element {
  const { colors } = useTheme();
  const handleDragOver = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(true);
    },
    [setIsDragging]
  );

  const handleDragLeave = useCallback(() => {
    setIsDragging(false);
  }, [setIsDragging]);

  const handleDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(false);
      const droppedFiles = Array.from(e.dataTransfer.files).filter((f) => {
        const lower = f.name.toLowerCase();
        const hasValidExt = lower.endsWith('.csv') || lower.endsWith('.xlsx');
        const isArtifact = ARTIFACT_PREFIXES.some(p => f.name.startsWith(p));
        return hasValidExt && !isArtifact;
      }) as UploadedFile[];
      onFilesSelected(droppedFiles);
    },
    [onFilesSelected, setIsDragging]
  );

  const handleBrowse = useCallback(() => {
    const input = document.createElement("input");
    input.type = "file";
    input.multiple = true;
    input.accept = ACCEPTED_EXTENSIONS.join(",");
    input.onchange = (e: Event) => {
      const target = e.target as HTMLInputElement;
      if (target.files) {
        const selectedFiles = Array.from(target.files) as UploadedFile[];
        onFilesSelected(selectedFiles);
      }
    };
    input.click();
  }, [onFilesSelected]);

  return (
    <View
      style={Platform.OS === 'web'
        ? {
            borderRadius: 16,
            borderWidth: 2,
            borderStyle: 'dashed' as any,
            borderColor: isDragging ? colors.gold : colors.borderMedium,
            backgroundColor: isDragging ? 'rgba(250,204,21,0.05)' : 'rgba(39,39,42,0.3)',
            overflow: 'hidden',
          }
        : {
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.background,
            overflow: 'hidden',
          }
      }
    >
      {Platform.OS === "web" ? (
        <div
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          style={{ padding: 0 }}
        >
          <View style={{ alignItems: 'center', justifyContent: 'center', paddingVertical: 48, paddingHorizontal: 24, gap: 16 }}>
            {/* Upload icon */}
            <View style={{ width: 64, height: 64, borderRadius: 16, backgroundColor: isDragging ? 'rgba(241,190,72,0.2)' : colors.borderLight, alignItems: 'center', justifyContent: 'center' }}>
              <Text style={{ fontSize: 32 }}>{isDragging ? "📂" : "☁️"}</Text>
            </View>

            {/* Heading */}
            <View style={{ alignItems: 'center', gap: 4 }}>
              <Text style={{ fontSize: 16, fontWeight: '600', textAlign: 'center', color: colors.text }}>
                {isDragging ? "Release to upload" : "Drop files here"}
              </Text>
              <Text style={{ fontSize: 14, color: colors.textMuted, textAlign: 'center' }}>
                or{" "}
                <Text
                  style={{ color: colors.gold, fontWeight: '600', cursor: "pointer" } as any}
                  onPress={handleBrowse}
                >
                  browse your device
                </Text>
              </Text>
            </View>

            {/* Accepted types */}
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'center', marginTop: 4 }}>
              <Text style={{ fontSize: 12, color: colors.textMuted, width: '100%', textAlign: 'center', marginBottom: 4 }}>
                Accepted file types:
              </Text>
              {ACCEPTED_EXTENSIONS.map((ext) => (
                <View key={ext} style={{ paddingHorizontal: 8, paddingVertical: 2, backgroundColor: colors.borderLight, borderRadius: 6 }}>
                  <Text style={{ fontSize: 12, color: colors.textSecondary, fontFamily: 'monospace' }}>{ext}</Text>
                </View>
              ))}
            </View>

            <Text style={{ fontSize: 12, color: colors.textFaint, marginTop: 4 }}>Max file size: 50 MB</Text>
          </View>
        </div>
      ) : (
        // Native (iOS/Android) — document picker
        <TouchableOpacity
          onPress={async () => {
            const result = await DocumentPicker.getDocumentAsync({
              type: [
                'text/csv',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/comma-separated-values',
              ],
              multiple: true,
              copyToCacheDirectory: true,
            });
            if (result.canceled) return;
            const picked: UploadedFile[] = result.assets.map((a) => ({
              name: a.name,
              size: a.size ?? 0,
              type: a.mimeType ?? '',
            }));
            onFilesSelected(picked);
          }}
        >
          <View style={{ alignItems: 'center', justifyContent: 'center', paddingVertical: 48, paddingHorizontal: 24, gap: 12 }}>
            <View style={{ width: 64, height: 64, borderRadius: 16, backgroundColor: colors.borderLight, alignItems: 'center', justifyContent: 'center' }}>
              <Text style={{ fontSize: 32 }}>📂</Text>
            </View>
            <View style={{ alignItems: 'center', gap: 4 }}>
              <Text style={{ fontSize: 16, fontWeight: '600', color: colors.text, textAlign: 'center' }}>
                Tap to browse files
              </Text>
              <Text style={{ fontSize: 13, color: colors.textMuted, textAlign: 'center' }}>
                CSV and XLSX files accepted
              </Text>
            </View>
          </View>
        </TouchableOpacity>
      )}
    </View>
  );
}